using DirectoryService.Application.Abstractions;
using DirectoryService.Contracts.Departments;

namespace DirectoryService.Application.Departments.Queries.GetRootDepartmentsWithChilden;

public record GetRootDepartmentsWithChildenCommand(GetRootDepartmentsWithChildenRequest Request) : ICommand;