using DirectoryService.Application.Abstractions;
using DirectoryService.Contracts.Departments.GetRootDepartmentsWithChilden;

namespace DirectoryService.Application.Departments.Queries.GetRootDepartmentsWithChilden;

public record GetRootDepartmentsWithChildenQuery(GetRootDepartmentsWithChildenRequest Request) : IQuery;